# Arbitrum Chain Configuration
# Chain-specific settings for Arbitrum One

[chain]
name = "arbitrum"
chain_id = 42161
native_token = "ETH"
native_decimals = 18
block_time_sec = 0.25  # Very fast blocks

[rpc]
primary = "https://arb1.arbitrum.io/rpc"
fallback = [
    "https://arbitrum-mainnet.infura.io/v3/${INFURA_KEY}",
    "https://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}",
    "https://arbitrum.public-rpc.com"
]
max_retries = 3
timeout_ms = 3000  # Faster timeouts due to lower latency
rate_limit_per_sec = 10

[websocket]
primary = "wss://arb-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
fallback = [
    "wss://arbitrum-mainnet.infura.io/ws/v3/${INFURA_KEY}",
    "wss://arbitrum.publicnode.com"
]

[dex]
[dex.uniswap_v3]
enabled = true
factory = "0x1F98431c8aD98523631AE4a59f267346ea31F984"
quoter = "0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6"

[dex.sushiswap]
enabled = true
factory = "0xc35DADB65012eC5796536bD9864eD8773aBc74C4"

[dex.camelot]
enabled = true
factory = "0x6EcCab422D763aC031210895C81787E87B43A652"

[tokens]
[tokens.WETH]
address = "0x82aF49447D8a07e3bd95BD0d56f35241523fBab1"
decimals = 18
symbol = "WETH"

[tokens.USDC]
address = "0xaf88d065e77c8cC2239327C5EDb3A432268e5831"
decimals = 6
symbol = "USDC"

[tokens.USDT]
address = "0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9"
decimals = 6
symbol = "USDT"

[tokens.ARB]
address = "0x912CE59144191C1204E64559FE8253a0e49E6548"
decimals = 18
symbol = "ARB"

[gas]
max_price_gwei = 10  # L2 has lower gas prices
priority_fee_gwei = 0.1
gas_limit_swap = 300000
gas_limit_arbitrage = 600000