# Polygon Chain Configuration
# Chain-specific settings for Polygon (Matic) Network

[chain]
name = "polygon"
chain_id = 137
native_token = "MATIC"
native_decimals = 18
block_time_sec = 2

[rpc]
primary = "https://polygon-rpc.com"
fallback = [
    "https://rpc-mainnet.matic.network",
    "https://rpc-mainnet.maticvigil.com",
    "https://polygon-mainnet.g.alchemy.com/v2/demo"
]
max_retries = 3
timeout_ms = 5000
rate_limit_per_sec = 5

[websocket]
primary = "wss://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
fallback = [
    "wss://polygon-bor.publicnode.com",
    "wss://polygon.drpc.org"
]
reconnect_interval_sec = 5
max_reconnects = 10

[dex]
# Supported DEX protocols on Polygon
[dex.uniswap_v2]
enabled = true
factory = "0x5757371414417b8C6CAad45bAeF941aBc7d3Ab32"  # QuickSwap
init_code_hash = "0x96e8ac4277198ff8b6f785478aa9a39f403cb768dd02cbee326c3e7da348845f"

[dex.uniswap_v3]
enabled = true
factory = "0x1F98431c8aD98523631AE4a59f267346ea31F984"
quoter = "0xb27308f9F90D607463bb33eA1BeBb41C27CE5AB6"

[dex.sushiswap]
enabled = true
factory = "0xc35DADB65012eC5796536bD9864eD8773aBc74C4"
init_code_hash = "0xe18a34eb0e04b04f7a0ac29a6e80748dca96319b42c54d679cb821dca90c6303"

[pools]
# Important pools to track
[pools.wmatic_usdc]
address = "0x6e7a5FAFcec6BB1e78bAE2A1F0B612012BF14827"
token0 = "WMATIC"
token1 = "USDC"
protocol = "QuickSwapV2"

[pools.weth_usdc]
address = "0x45dDa9cb7c25131DF268515131f647d726f50608"
token0 = "WETH"
token1 = "USDC"
protocol = "UniswapV3"
fee_tier = 500

[tokens]
# Common tokens on Polygon
[tokens.WMATIC]
address = "0x0d500B1d8E8eF31E21C99d1Db9A6444d3ADf1270"
decimals = 18
symbol = "WMATIC"

[tokens.USDC]
address = "0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174"
decimals = 6
symbol = "USDC"

[tokens.USDT]
address = "0xc2132D05D31c914a87C6611C10748AEb04B58e8F"
decimals = 6
symbol = "USDT"

[tokens.WETH]
address = "0x7ceB23fD6bC0adD59E62ac25578270cFf1b9f619"
decimals = 18
symbol = "WETH"

[tokens.DAI]
address = "0x8f3Cf7ad23Cd3CaDbD9735AFf958023239c6A063"
decimals = 18
symbol = "DAI"

[gas]
# Gas price settings for Polygon
max_price_gwei = 500
priority_fee_gwei = 30
gas_limit_swap = 250000
gas_limit_arbitrage = 500000