# Torq Development Environment Configuration
# Overrides for local development and testing

[global]
socket_dir = "/tmp/torq_dev"
log_dir = "./logs"
log_level = "debug"
pid_dir = "./.pids"

# Service-specific configurations
[services]

[services.market_data_relay]
enabled = true
health_port = 8001
priority = 10
# socket_path = "/tmp/torq/market_data.sock"  # Default

[services.signal_relay]  
enabled = true
health_port = 8002
priority = 20
# socket_path = "/tmp/torq/signals.sock"  # Default

[services.execution_relay]
enabled = true
health_port = 8003
priority = 30
# socket_path = "/tmp/torq/execution.sock"  # Default

[services.polygon_event_collector]
enabled = true
health_port = 8004
priority = 40
websocket = "ws://localhost:8546"  # Local node for testing

[services.polygon_pool_metadata]
enabled = true
health_port = 8010
priority = 45
rpc_primary = "http://localhost:8545"  # Local Polygon fork
rate_limit_per_sec = 100  # No rate limiting for local
retry_interval_sec = 5  # Faster retries in dev

[services.flash_arbitrage]
enabled = true
health_port = 8005
priority = 50

[services.dashboard_websocket]
enabled = true
health_port = 8006
priority = 60

[services.kraken_collector]
enabled = false  # Optional for development
health_port = 8007
priority = 70

[services.binance_collector]
enabled = false  # Optional for development
health_port = 8008
priority = 80

[services.coinbase_collector]
enabled = false  # Optional for development
health_port = 8009
priority = 90