# Torq Docker Environment Configuration

# Docker-specific paths
socket_dir = "/app/sockets"
log_dir = "/app/logs"
pid_file = "/app/system.pids"

# Service-specific configurations for Docker
[services]

[services.market_data_relay]
enabled = true
health_port = 8001
priority = 10

[services.signal_relay]  
enabled = true
health_port = 8002
priority = 20

[services.execution_relay]
enabled = true
health_port = 8003
priority = 30

[services.polygon_publisher]
enabled = true
health_port = 8004
priority = 40

[services.flash_arbitrage]
enabled = true
health_port = 8005
priority = 50

[services.dashboard_websocket]
enabled = true
health_port = 8006
priority = 60

[services.kraken_collector]
enabled = true
health_port = 8007
priority = 70

[services.binance_collector]
enabled = true
health_port = 8008
priority = 80

[services.coinbase_collector]
enabled = true
health_port = 8009
priority = 90