# Torq Testing Environment Configuration

# Testing paths with unique identifiers
socket_dir = "/tmp/torq-test"
log_dir = "/tmp/torq_logs_test"
pid_file = "/tmp/torq_test.pids"

# Service-specific configurations for testing
[services]

[services.market_data_relay]
enabled = true
health_port = 7001  # Testing ports
priority = 10

[services.signal_relay]  
enabled = true
health_port = 7002
priority = 20

[services.execution_relay]
enabled = true
health_port = 7003
priority = 30

[services.polygon_publisher]
enabled = false  # Disabled for unit tests
health_port = 7004
priority = 40

[services.flash_arbitrage]
enabled = false  # Disabled for unit tests  
health_port = 7005
priority = 50

[services.dashboard_websocket]
enabled = false  # Disabled for unit tests
health_port = 7006
priority = 60

[services.kraken_collector]
enabled = false  # Disabled for unit tests
health_port = 7007
priority = 70

[services.binance_collector]
enabled = false  # Disabled for unit tests
health_port = 7008
priority = 80

[services.coinbase_collector]
enabled = false  # Disabled for unit tests
health_port = 7009
priority = 90